DjangoAssignment/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('item/', views.item_list, name='item_list'),
    path('item/<int:pk>/', views.item_detail, name='item_detail'),
    path('item/register/', views.item_register, name='item_register'),
    path('item/<int:pk>/update/', views.item_update, name='item_update'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),
    path('account/', views.account_list, name='account_list'),
    path('account/<int:pk>/', views.account_detail, name='account_detail'),
    path('account/register/', views.account_register, name='account_register'),
    path('account/<int:pk>/update/', views.account_update, name='account_update'),
    path('account/<int:pk>/delete/', views.account_delete, name='account_delete'),
]

item/models.py
from django.db import models

class Account(models.Model):
    name = models.CharField(max_length=100)
    call = models.CharField(max_length=100)
    address = models.TextField()

class Item(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(blank=True)
    content = models.TextField()
    price = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

item/forms.py
from django import forms
from .models import Item, Account

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item  # ModelForm을 이용하면, Model 내역에 맞게 손쉽게 정의 가능
        fields = '__all__' # 모든 필드가 자동 지정이 됨.

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = '__all__'

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Item, Account
from .forms import ItemForm, AccountForm


def item_list(request):
    item__list = Item.objects.all()

    context = {'item_list': item__list}  # 왼쪽이 내가 쓸 변수 이름, 오른쪽이 불러올 객체
    return render(request, 'item/item_list.html', context)

def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'item/item_detail.html', {
        'item': item,
    })

def item_register(request):
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)  # ModelForm에서 제공하는 기능
            item.save()
            pk = item.id
            url = reverse('item:item_detail', kwargs={'pk': pk})
            return redirect(to=url)
    else:
        form = ItemForm
    return render(request, 'item/item_register.html', {
        'form': form,
    })

def item_update(request, pk):
    item = Item.objects.get(id=pk)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.save()
            pk = item.id
            url = reverse('item:item_detail', kwargs={'pk': pk})
            return redirect(to=url)
    else:
        form = ItemForm(instance=item)
    context = {'form': form}
    return render(request, 'item/item_register.html', context)


def item_delete(request, pk):
    item = Item.objects.get(id=pk)
    item.delete()

    url = reverse('item:item_list')
    return redirect(to=url)

def account_list(request):
    account__list = Account.objects.all()

    context = {'account_list': account__list}
    return render(request, 'item/account_list.html', context)

def account_detail(request, pk):
    account = get_object_or_404(Account, pk=pk)
    # my_account = Item.get.objects.get(Account__name)
    return render(request, 'item/account_detail.html', {
        'account': account
    })

# def account_register(request, account=None):
#     if request.method == "POST":
#         form = AccountForm(request.POST, instance=account)
#         if form.is_valid():
#             account = form.save()  # ModelForm에서 제공하는 기능
#             return redirect(account)
#     else:
#         form = AccountForm(instance=account)
#     return render(request, 'item/account_register.html', {
#         'form': form,
#     })
#
# def account_update(request, pk):
#     account = get_object_or_404(Account, pk=pk)
#     return account_register(request, account)

def account_register(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.save()
            pk = account.id
            url = reverse('item:account_detail', kwargs={'pk': pk})
            return redirect(to=url)
    else:
        form = AccountForm
    context = {'form': form}
    return render(request, 'item/account_register.html', context)

def account_update(request, pk):
    account = Account.objects.get(id=pk)
    if request.method == 'POST':
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            account = form.save(commit=False)
            account.save()
            pk = account.id
            url = reverse('item:account_detail', kwargs={'pk': pk})
            return redirect(to=url)
    else:
        form = AccountForm(instance=account)
    context = {'form': form}
    return render(request, 'item/account_register.html', context)

def account_delete(request, pk):
    account = Account.objects.get(id=pk)
    account.delete()

    url = reverse('item:account_list')
    return redirect(to=url)

item/templates/item/account_detail.html
{% extends 'item/layout.html' %}
{% block content %}
{#    {% load humanize %}#}
    <h1>Account Detail</h1>
    <b>{{ account.name }}</b>
    <br/>
    {{ account.call }}
    <br/>
    {{ account.address }}    <br/>
    <b>거래 상품 목록</b>
    <br/>
    {% for item in account.item_set.all %}
    {{ item.title }}
    {% endfor %}
    <br/><br/>
    <hr/>
{#    삭제, 목록, 수정#}
    <a href="{% url 'item:account_delete' account.pk %}?next={{ request.path }}">삭제</a>
    <a href="/account/">목록</a>
    <a href="{% url 'item:account_update' account.pk %}?next={{ request.path }}">수정</a>

{% endblock %}

item/templates/item/account_list.html
{% extends 'item/layout.html' %}

{% block content %}
<h1>Account List</h1>
    <p>거래처 목록 페이지 입니다. 거래처를 자세히 보려면 거래처 블록을 클릭하세요.</p>

{% for account in account_list %}
    <a href="{% url 'item:account_detail' account.pk %}"><h2>{{ account.name }}</h2></a>
{#    app name : name space#}
    <img src="">
    <br/>
    {{ account.call }}
    <br/>
    {{ account.address }}
    <br/>
{% endfor %}
{% endblock %}

item/templates/item/account_register.html
{% extends 'item/layout.html' %}
{% block content %}
<h1>Account Register</h1>
<p>거래처 등록 및 수정 페이지입니다. </p>

<form method="post" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}
    <table class="table table-bordered">
        {{ form.as_table }}
    </table>
    <button type="submit">저장</button>
</form>
{% endblock %}

item/templates/item/item_detail.html
{% extends 'item/layout.html' %}
{% block content %}
{#    {% load humanize %}#}
    <h1>Item Detail</h1>
    {% if item.image %}
    <img src="{{ item.image.url }}" style="max-width: 30%;" />
    {% endif %}
    <br/>
    <b>{{ item.title }}</b>
    <br/>
    가격 : {{ item.price }}
    <br/>
    남은 수량 : {{ item.amount }}
    <br/><br/>
    제품 설명 :
    <br/><br/>
    {{ item.title }} 설명입니다.
    <br/>
    {{ item.content }}
    <br/><br/>
    <b>거래처 :</b> {{ item.account }}
    <hr/>
{#    삭제, 목록, 수정#}
    <a href="{% url 'item:item_delete' item.pk %}">삭제</a>
    <a href="/item/">목록</a>
    <a href="{% url 'item:item_update' item.pk %}">수정</a>

{% endblock %}

item/templates/item/item_list.html
{% extends 'item/layout.html' %}

{% block content %}
<h1>Item List</h1>
    <p>해당 상품의 설명을 보려면 이미지를 클릭해 주세요.</p>

{% for item in item_list %}
    <span>
    <a href="{% url 'item:item_detail' item.pk %}">{{ item.title }}</a>
    {% if item.image %}
        <img src="{{ item.image.url }}" style="max-width: 30%;" / >
    {% endif %}

    <br/>
    가격 : {{ item.price }}
    <br/>
    남은 수량 : {{ item.amount }}
    <br/>
{% endfor %}</span>
{% endblock %}

item/templates/item/item_register.html
{% extends 'item/layout.html' %}
{% block content %}
<h1>Item Register</h1>
<p>상품 등록 및 수정 페이지입니다. </p>

<form method="post" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}
    <table class="table table-bordered">
        {{ form.as_table }}
    </table>
    <input type="submit" value="저장" class="btn btn-primary" />
</form>
{% endblock %}

item/templates/item/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        h1 {text-align: center;}
        p {text-align: center;}
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'item:item_list' %}">Inventory Manage</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
    <span class="navbar-text">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'item:item_register' %}">상품 등록<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'item:account_register' %}">거래처 등록</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'item:account_list' %}">거래처 관리</a>
      </li>
    </ul>
    </span>
  </div>
</nav>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>